name: Build MineFunKing

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install g++-multilib
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install g++-multilib

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}